surveyform/config/routes.rb
Surveyform::Application.routes.draw do
  resources :surveys
end

surveyform/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

surveyform/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

surveyform/app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

surveyform/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new
    3.times do 
      question = @survey.questions.build 
      4.times { question.answers.build }
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :ok }
    end
  end
end

surveyform/app/helpers/surveys_helper.rb
module SurveysHelper
end

surveyform/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Surveyform</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

surveyform/app/views/surveys/_answer_fields.html.erb
<p>
  <%= f.label :content, "Answer" %> <br/>
  <%= f.text_field :content %>
  <%= f.check_box :_destroy -%>
  <%= f.label :_destroy, "Remove"-%>
</p>

surveyform/app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render 'question_fields', :f => builder -%>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

surveyform/app/views/surveys/_question_fields.html.erb
<p>
  <%= f.label :content, "Question" %> <br/>
  <%= f.text_area :content %>
  <%= f.check_box :_destroy -%>
  <%= f.label :_destroy, "Remove Question"-%>
</p>
<%= f.fields_for :answers do |builder| -%>
  <%= render 'answer_fields', :f => builder-%>
<% end %>

surveyform/app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

surveyform/app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.name %></td>
    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

surveyform/app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

surveyform/app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= h @survey.name %>
</p>

<ol>
  <% for question in @survey.questions %>
    <li> <%= h question.content %> </li>
    <ul>
      <% for answer in question.answers %>
        <li><%= h answer.content %></li>
      <% end %>
    </ul>
  <% end %>
</ol>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>